### ISSUE TITLE
UI Widget not showing current 'time'

### ISSUE THREAD

**Issue by toshi0383** [imReker/FlutterHomeWidget#2]
Any ideas? I'm using Pixel 3a (API R) emulator.
![Screenshot_1610359747](https://user-images.githubusercontent.com/6007952/104167913-83c07380-5440-11eb-9e83-49551c9b271d.png)

**Comment by imReker** [comment]
Yes because the flutter code of UI widget does not show time :)

**Comment by toshi0383** [comment]
Well, it does mate?
<img width="1071" alt="スクリーンショット 2021-01-11 22 27 29" src="https://user-images.githubusercontent.com/6007952/104188198-33570f00-545c-11eb-9aa0-924b14186f3f.png">
 If I change the initial value of `String time`, it shows up.
Problem is, it's not updated at all?

**Comment by imReker** [comment]
You need update widget from Android side manually.
Because the widget is not a normal Flutter app. Android init a new Flutter engine, engine run widget Flutter app, a screenshot is taken, Flutter app terminated, screenshot convert to Bitmap and send to Android widget system.
