### ISSUE TITLE
Can button receive events on UIWidget ?

### ISSUE THREAD

**Issue by answer0732** [imReker/FlutterHomeWidget#3]

**Comment by suztomo** [comment]
No, use Link to detect touch.

https://stackoverflow.com/questions/64230355/perform-a-deeplink-from-swiftui-widget-on-tap/64230963

**Comment by answer0732** [comment]
> No, use Link to detect touch.
> 
> https://stackoverflow.com/questions/64230355/perform-a-deeplink-from-swiftui-widget-on-tap/64230963

thanks ! but i am using android, what should I do?

**Comment by suztomo** [comment]
I'm afraid that I don't develop Android widgets.

**Comment by answer0732** [comment]
> I'm afraid that I don't develop Android widgets.

thanks anyway !

**Comment by imReker** [comment]
> > No, use Link to detect touch.
> > https://stackoverflow.com/questions/64230355/perform-a-deeplink-from-swiftui-widget-on-tap/64230963
> 
> thanks ! but i am using android, what should I do?

Similar to iOS, by using `PendingIntent`, please read the documents of Android Widget.
